### ISSUE TITLE
Possible to add script before _paq.push(['trackPageView']);?

### ISSUE THREAD

**Issue by kslstn** [jop-software/astro-matomo#15]
For reasons beyond me, adding Matomo with the normal scripts didn't work, so I was happy to find this integration. Thank you!

I used to track 404s using with [this recommended approach](https://matomo.org/faq/how-to/faq_60/) that relies on changing the page title before the view is tracked. 

With the integration, I can't access the script directly anymore. Would it be somehow possible to track 404s?

**Comment by tordans** [comment]
I am using this in my `404.astro`

```html
  <script>
      window._paq = window._paq || []
      window._paq.push([
        'setDocumentTitle',
        `404/URL = ${encodeURIComponent(document.location.pathname + document.location.search)} /From = ${encodeURIComponent(document.referrer)}`,
      ])
  </script>
```

I am using https://github.com/felix-berlin/astro-matomo/ but this package should work the same because it uses the same astro hook to inject the script.

**Comment by kslstn** [comment]
Yes, that works, thank you!
